import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { VideoMlGeneratedModule, VideoMlGeneratedSharedModule } from './generated/module';
import { VideoMlValidator, registerValidationChecks } from './video-ml-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type VideoMlAddedServices = {
    validation: {
        VideoMlValidator: VideoMlValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type VideoMlServices = LangiumServices & VideoMlAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const VideoMlModule: Module<VideoMlServices, PartialLangiumServices & VideoMlAddedServices> = {
    validation: {
        VideoMlValidator: () => new VideoMlValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createVideoMlServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    VideoMl: VideoMlServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        VideoMlGeneratedSharedModule
    );
    const VideoMl = inject(
        createDefaultModule({ shared }),
        VideoMlGeneratedModule,
        VideoMlModule
    );
    shared.ServiceRegistry.register(VideoMl);
    registerValidationChecks(VideoMl);
    return { shared, VideoMl };
}
